export enum StorageItem {
  PALETTE_MODE = 'PALETTE_MODE',
  PRIMARY_COLOR = 'PRIMARY_COLOR',
  SECONDARY_COLOR = 'SECONDARY_COLOR',
  ERROR_COLOR = 'ERROR_COLOR',
  WARNING_COLOR = 'WARNING_COLOR',
  INFO_COLOR = 'INFO_COLOR',
  SUCCESS_COLOR = 'SUCCESS_COLOR',
}
